s1=int(input("Enter mark for tamil:"))
s2=int(input("Enter mark for english:"))
s3=int(input("Enter mark for maths:"))
s4=int(input("Enter mark for social science:"))
s5=int(input("Enter mark for science:"))
Total=s1+s2+s3+s4+s5
print("Total mark =",Total)
avg=Total/5
print("Average =",avg)